### PR TITLE
[15.0] [FIX] membership_extension:Add memberhsip manager group to admin user

### PR DESCRIPTION
**Pull request by bvanjeelharia**
Fixes https://github.com/OCA/vertical-association/issues/141

### CODE REVIEW

**Comment by bvanjeelharia** [comment]
I reverified in the module and found that the group is getting applied to admin user through demo file, so I believe it should be removed from there and added directly.Please suggest if this makes sense or not

**Review by chienandalu — COMMENTED** [review]
Thanks @bvanjeelharia 

Yes I think it's ok and that the demo declaration can go away

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
/ocabot merge minor

Please move it to upper version.

**Comment by chienandalu** [comment]
Please forward port it to v16 if needed

**Comment by xavivars** [comment]
v16 still has this problem

**Comment by chienandalu** [comment]
> v16 still has this problem

Ok, @bvanjeelharia didn't make the fw. But any contribution is welcome :wink:

**Pull request merged**
