### PR TITLE
[16.0][MIG] membership_withdrawal

### PR DESCRIPTION
**Pull request by carmenbianca**
- [x] Depend on https://github.com/OCA/vertical-association/pull/132

Ping @robinkeunen @PierrickBrun

### CODE REVIEW

**Comment by rafaelbn** [comment]
- [x] Depend on https://github.com/OCA/vertical-association/pull/132

WIP until that PR is merged 😄

**Comment by fcvalgar** [comment]
@carmenbianca can you rebase? please

**Comment by carmenbianca** [comment]
@fcvalgar done, thank you

**Comment by fcvalgar** [comment]
I have an error buying a membership on the memberships tab of the contact. 
The sale of the membership from the invoice works correctly. @carmenbianca 

https://www.loom.com/share/f22e4bfd7ea74825b60086144417f04b

@moduon MT-1835

**Comment by carmenbianca** [comment]
@fcvalgar This is not different behaviour from Odoo 14. Odoo 16 just changed where to change the requisite setting… See video.

[out.webm](https://user-images.githubusercontent.com/12065945/211520623-28147f90-b0d1-4ffb-8811-a1fc4f561c71.webm)

**Review by PierrickBrun — APPROVED** [review]

**Comment by chienandalu** [comment]
@fcvalgar can you update yor review?

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @carmenbianca .

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
