### PR TITLE
[16.0][MIG] membership_initial_fee

### PR DESCRIPTION
**Pull request by edlopen**
Standard migration.

@moduon MT-1828

@yajo @EmilioPascual @Shide @rafaelbn review this PR when you can. Thank you!

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by yajo — APPROVED** [review]

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM, thank you @edlopen .

image

image

**Review by EmilioPascual — APPROVED** [review]
Code and functional review

**Comment by edlopen** [comment]
@rafaelbn functional and code reviews are ok. Could you merge this please? Thank you!

**Review by rafaelbn — APPROVED** [review]
/ocabot migration patch

**Pull request merged**
