### PR TITLE
[12.0][FIX] membership_delegated_partner Weblate it.po error

### PR DESCRIPTION
**Pull request by mymage**
Update of it.po that generate an error on Weblate

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why are you doing this here instead of Weblate?

https://odoo-community.org/page/translate

**Comment by mymage** [comment]
> Why are you doing this here instead of Weblate?
> 
> https://odoo-community.org/page/translate

Because when I try to translate it on Weblate, it raise a server error.
Let me know if there is another way to do/fix it.

**Comment by pedrobaeza** [comment]
I think that has been something temporary today. Please try again.

**Comment by mymage** [comment]
> I think that has been something temporary today. Please try again.

Ok, no problem. I opened this because in another case ([management-system/#499](https://github.com/OCA/management-system/pull/499)) I did this way.
I will try for some days and comment here on positive/negative result.

**Review by rafaelbn — APPROVED** [review]
Similar to https://github.com/OCA/management-system/pull/501

**Pull request closed without merging**
