### PR TITLE
[15.0][MIG] membership_variable_period

### PR DESCRIPTION
**Pull request by flachica**
Standard migration from 14.0 to 15.0. All the instruction for testing in the README

- [x] This PR depends on https://github.com/OCA/vertical-association/pull/128

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @flachica , please could you check test and try to fix runboat in order to test it please? Thank you very much!

**Comment by flachica** [comment]
@rafaelbn This PR need #128 be merged

**Comment by rafaelbn** [comment]
@flachica rebase

/ocabot rebase

**Comment by rafaelbn** [comment]
Hello @carmenbianca , please could you review this one? Cross review is a good practice! 😄

**Comment by rafaelbn** [comment]
Please @fcvaliente could you review?

**Comment by rafaelbn** [comment]
Please @fcvalgar could you review?

**Review by fcvalgar — APPROVED** [review]
Functional review ok in runboat. 
Thank you @flachica

**Comment by fcvalgar** [comment]
internal @moduon MT-1834

**Review by carmenbianca — APPROVED** [review]
LGTM

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
