### PR TITLE
[17.0][MIG] membership_variable_period: Migration to 17.0

### PR DESCRIPTION
**Pull request by RogerSans**
Standard migration
T-6475

@HaraldPanten
@ValentinVinagre

This module depends of membership_extension https://github.com/OCA/vertical-association/pull/170

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@pedrobaeza could you assign this migration to us?

THX

**Comment by ValentinVinagre** [comment]
@luis-ron could you review?

**Comment by rafaelbn** [comment]
@moduon MT-7144

**Review by fcvalgar — APPROVED** [review]
Functional review.

LGTM, Thank you @RogerSans.

image

image

**Review by Gelojr — APPROVED** [review]
LGTM Thanks
https://www.loom.com/share/9cf5858a1f4445f5b0630a90e12f51af?sid=b3af5fd8-117f-4101-a000-c5af93d92de6

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
