### PR TITLE
[FIX] membership_delegated/fee: Solves an incompatibility between both

### PR DESCRIPTION
**Pull request by chienandalu**
FW port from #54

Without changing inter-dependencies, using dynamic code detection.

TT27686 cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking as direct fw-port:

/ocabot merge patch

Needed in 13/14?

**Comment by pedrobaeza** [comment]
Please fix the Travis problem

**Review by marcelsavegnago — APPROVED** [review]

**Comment by chienandalu** [comment]
Fixed. Yes, it will be necessary for future versions as well

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please do the corresponding PRs.

**Pull request merged**
