### PR TITLE
[10.0][FIX] membership_extension: Fix refund validate if origin is void

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza @chienandalu

**Review by chienandalu — APPROVED** [review]
LGTM :+1:

**Comment by rousseldenis** [comment]
> LGTM

Thanks.

IMHO something should be done to avoid searching on origin (a field that link together records or ...)

**Comment by pedrobaeza** [comment]
A bit old for us, but straight-forward:

/ocabot merge patch

**Pull request merged**
