### PR TITLE
[14.0] [FIX] membership_extension: duplicated membership product menu entry

### PR DESCRIPTION
**Pull request by primes2h**
immagine

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please include the name of the module in the commit message and PR title.

https://www.odoo.com/documentation/14.0/developer/misc/other/guidelines.html#commit-message-structure

**Comment by primes2h** [comment]
> Please include the name of the module in the commit message and PR title.
> 
> https://www.odoo.com/documentation/14.0/developer/misc/other/guidelines.html#commit-message-structure

Done, thank you!

**Review by pedrobaeza — APPROVED** [review]

**Review by marcelofrare — APPROVED** [review]
LGTM

**Pull request merged**
