### PR TITLE
[15.0][MIG] contract_membership_delegated_partner: Migration to 15.0

### PR DESCRIPTION
**Pull request by chienandalu**
- Standard migration

cc @Tecnativa TT42034

please review @ernestotejeda @ernesto-garcia-tecnativa

### CODE REVIEW

**Review by ernestotejeda — APPROVED** [review]

**Review by ernesto-garcia-tecnativa — APPROVED** [review]
Code and functional review OK

**Comment by pedrobaeza** [comment]
/ocabot migration contract_membership_delegated_partner

Tests are red.

**Comment by chienandalu** [comment]
I promoted `membership_delegated_partner` to stable to avoid development status chain issues and because, well, it's been stable for many years now :)

**Pull request merged**
