### PR TITLE
[16.0][MIG] membership prorate: Migration to version 16.0

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Review by espo-tony — APPROVED** [review]

**Comment by rafaelbn** [comment]
@moduon MT-1829

Please @fcvalgar @edlopen please review! ❤️ Thank you!

**Review by fcvalgar — APPROVED** [review]
Functional review,

[OCA - membership_prorate QA - MT-1829 - Watch Video](https://www.loom.com/share/585f484f4a1f4be1b8d70571e9a9cdc9)

LGTM, thank you @bvanjeelharia

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
