### PR TITLE
[14.0] [ADD] new module membership_receipt

### PR DESCRIPTION
**Pull request by primes2h**
This module adds the possibility to manage membership using receipts.

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
I don't understand well the concept of `receipt` and the purpose of the module. Could you explain it a little bit more?

**Comment by primes2h** [comment]
> I don't understand well the concept of `receipt` and the purpose of the module. Could you explain it a little bit more?

Hi David, thanks for the heads-up.
I mean the use of sale receipts instead of customer invoices to manage memberships.
In some countries associations/nonprofit organizations don't have VAT code but only fiscal code, so they have to issue sale receipts instead of invoices as accounting document.

**Comment by primes2h** [comment]
@chienandalu 
This module adds a button in the wizard in order to join membership with a sale receipt instead of an invoice.

immagine

**Comment by primes2h** [comment]
> In some countries associations/nonprofit organizations don't have VAT code but only fiscal code, so they have to issue sale receipts instead of invoices as accounting document.

P.S.: With fiscal code number I mean TIN (Taxpayer Identification Number).
https://taxing.it/italian-fiscal-code-number-tax-code-tin/

**Comment by primes2h** [comment]
@OCA/vertical-association-maintainers 
Could you reopen it please?

**Comment by chienandalu** [comment]
Done @primes2h

**Comment by primes2h** [comment]
@OCA/vertical-association-maintainers 
Could you reopen it please?

> Done @primes2h

Thanks!

**Review by marcelofrare — APPROVED** [review]
LGTM functionally it's ok.
Thanks @primes2h!

**Review by mymage — APPROVED** [review]
I's ok for me

**Comment by primes2h** [comment]
Updated README.

**Comment by rafaelbn** [comment]
Hello @primes2h ,

> In some countries associations/nonprofit organizations don't have VAT code but only fiscal code, so they have to issue sale receipts instead of invoices as accounting document.

Maybe, you are missing this repo: https://github.com/OCA/donation

https://github.com/OCA/donation/blob/14.0/donation/views/donation_tax_receipt.xml

😄 Take a look! Domations is a really 

PD https://github.com/OCA/donation/tree/8.0

> This project develops Odoo modules for advanced management of donations. With the modules available in this project, you can manage:
> 
>     simple donations via checks, cash, credit card, online payment and wire transfers.
>     recurring donations via direct debit and credit transfers.
>     tax receipts that are sent back to donors, either one-time or annual tax receipts.
>     edition of the thank you letter.
> 
> The donations modules are fully integrated with the accounting and payment modules of Odoo. When you validate a donation in Odoo, the corresponding accounting entries are automatically generated. Donations via credit transfer are identified and generated from the bank statements of Odoo. If you also install the OCA module for [SEPA direct debit](https://github.com/OCA/bank-payment/tree/8.0/account_banking_sepa_direct_debit), you can organise your recurring donations via direct debit and easily generate the SEPA XML file for the bank.
> 
> These modules have been developped by the [Barroux Abbey](http://www.barroux.org/), a Benedictine Abbey located near the [Mont Ventoux](http://en.wikipedia.org/wiki/Mont_Ventoux) in France, who decided to publish these modules so that they can benefit to associations, NGOs and other religious organisations. These modules are fully mature: they are used in production at the Barroux Abbey since January 1st 2015.
> 
> The main developpers of the project are:
> 
>     Brother Bernard (Barroux Abbey)
>     Brother Irénée (Barroux Abbey)
>     Alexis de Lattre (Akretion)
> 
> Please refer to the README of each module to have more information about how to configure and use the modules.

**Comment by primes2h** [comment]
> Hello @primes2h ,
> 

> > This project develops Odoo modules for advanced management of donations. With the modules available in this project, you can manage:
> > ```
> > simple donations via checks, cash, credit card, online payment and wire transfers.
> > recurring donations via direct debit and credit transfers.
> > tax receipts that are sent back to donors, either one-time or annual tax receipts.
> > edition of the thank you letter.
> > ```
> >     
> > Please refer to the README of each module to have more information about how to configure and use the modules.

Hi @rafaelbn, thank you for pointing out this repo, I'll have a look. :+1:

**Pull request closed without merging**
