### PR TITLE
[15.0][MIG] membership_extension: Migration to 15.0

### PR DESCRIPTION
**Pull request by farzeni**
Standard migration from 14.0 to 15.0.

### CODE REVIEW

**Comment by flachica** [comment]
The commit message must be [MIG] membership_extension 15.0 instead module_extension

**Comment by flachica** [comment]
In order to be merge this PR you must write in #114

**Comment by rafaelbn** [comment]
Please @fcvalgar @Luisotto could you review functionality? Just contribution for OCA 😄

**Comment by rafaelbn** [comment]
After merging this PR we should review https://github.com/OCA/vertical-association/pull/130

For the School association of our children! Let's digitalize with OpenSource 😄

**Review by flachica — APPROVED** [review]
Functional Ok

You must squash some commits

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
