### PR TITLE
[MIG] membership_initial_fee,membership_prorrate: Migrated to 10.0

### PR DESCRIPTION
**Pull request by rigo1985**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @rigo1985, thanks for this contribution. Please make a single PR per module. Thanks!

**Comment by vonpupp** [comment]
Hello,

I don't have experience migrating modules but is there anything I could do to help on this PR? I am looking forward to implement credit card/paypal recurrent donations for an NGO and it seems that this module might suit that case fine.

Thank you for your efforts.

**Comment by pedrobaeza** [comment]
As stated, only one module per PR, please. And check Travis status.

**Comment by rafaelbn** [comment]
This PR has been splitted in:

- https://github.com/OCA/vertical-association/pull/25
- https://github.com/OCA/vertical-association/pull/26
- https://github.com/OCA/vertical-association/pull/27
- https://github.com/OCA/vertical-association/pull/28

**Pull request closed without merging**
