### PR TITLE
[MIG] membership_extension: Migration to 11.0

### PR DESCRIPTION
**Pull request by chienandalu**
Membership extension
====================

This module extends Odoo's membership management with the following features:

* Membership category
* Membership lines editable
* Do not calculate membership state from invoice status
* Start date of last membership period

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by pedrobaeza** [comment]
Please cherry-pick here 9b777a2235320a85c16b9c9a5383ac5f13e99e09

**Comment by rafaelbn** [comment]
Please @chienandalu here too. Review if all IMP and FIX from 10.0 are here. Thanks

**Comment by chienandalu** [comment]
Yes, they are.

**Comment by pedrobaeza** [comment]
Please check Travis

**Review by pedrobaeza — APPROVED** [review]
Ok, green! Please squash and I'm going to merge as this is a dependency for other PRs.

**Comment by chienandalu** [comment]
Yeah, it seems that now the sql logger must be muted to test `IntegrityError`

**Comment by chienandalu** [comment]
@pedrobaeza Rebased and green

**Comment by pedrobaeza** [comment]
Ok, merging. Please rebase dependent PRs.

**Pull request merged**
