### PR TITLE
[11.0][FIX] membership_extension: create new member_line after member_line cancel

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/vertical-association/issues/73

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking this as obvious

/ocabot merge patch

Does this apply to upper versions?

**Comment by astirpe** [comment]
Yes, also V12 is affected. I'm opening another PR.

**Comment by pedrobaeza** [comment]
@astirpe don't worry: I have already fixed it in the main branch and launch the new merge, which doesn't include your last commit.

**Pull request closed without merging**
