### PR TITLE
[15.0][FIX] membership_extension: Don't return early

### PR DESCRIPTION
**Pull request by pedrobaeza**
Follow-up of #159 after not getting answer

Don't return before consuming whole recordset.

@Tecnativa

### CODE REVIEW

**Comment by AlbertCabedo** [comment]
+1

**Review by chienandalu — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Comment by rafaelbn** [comment]
@pedrobaeza you can merge this FIX but test are failing

**Comment by pedrobaeza** [comment]
Tests failing is due to other module (and main branch is also red). It's in my backlog to fix the branch, but not able to do it for now.

**Comment by gaikaz** [comment]
I was about to create a PR for the exact fix on `16.0`
Could we get this merged and forward-ported?

**Review by gaikaz — APPROVED** [review]

**Review by hhgabelgaard — APPROVED** [review]
Tested, works

**Pull request merged**
