### PR TITLE
[FIX] broken Membership Products menu

### PR DESCRIPTION
**Pull request by lucode**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @chienandalu

**Comment by JordiBForgeFlow** [comment]
@lucode Has a valid ICLA. Not sure why github is not detecting it.

**Comment by pedrobaeza** [comment]
I think you have to mark it explicitly in his res.partner record in OCA instance.

**Comment by lucode** [comment]
yes I got the confirmation about my ICLA this morning.

Cheers Lucas

*ORG-IT, Organisations und IT Beratung*
Lucas C. Huber | +41 (0)52 366 66 90 | Mobiltelefon:+41 (0)79 702 50 72
_lucas.huber@org-it.ch_ <mailto:lucas.huber@org-it.ch> | Dickbuch 482 | 
CH-8354 Hofstetten | Switzerland

Am 07.08.2017 um 12:48 schrieb Jordi Ballester Alomar:

**Review by chienandalu — APPROVED** [review]
Thanks @lucode. Indeed the products menu option was unavailable once it had a child (wich is an annoying behavior)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
