### PR TITLE
[13.0][MIG] membership_extension

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Looks like some tests are failing

**Comment by astirpe** [comment]
@chienandalu tests updated!

**Comment by astirpe** [comment]
@chienandalu could you update your review?

**Comment by chienandalu** [comment]
@astirpe Please rebase your branch to get the last changes and resolve conflicts. I will try to take some time to properly review your PR :)

**Comment by astirpe** [comment]
@chienandalu done, thanks

**Comment by TheCloneMaster** [comment]
Code review, works perfect !

**Comment by pedrobaeza** [comment]
@chienandalu can you update your review?

**Review by chienandalu — COMMENTED** [review]
Ok. Tested. Looks good to me. Thanks @astirpe !

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
