### PR TITLE
[16.0][MIG] membership_variable_period

### PR DESCRIPTION
**Pull request by carmenbianca**
Migrated from v14.0. Tagging @flachica from #130 

- [x] Depends on https://github.com/OCA/vertical-association/pull/132

Ping @robinkeunen @PierrickBrun

### CODE REVIEW

**Comment by carmenbianca** [comment]
@rafaelbn rebased

**Comment by rafaelbn** [comment]
Runboat log

```
+ bash /runboat/runboat-clone-and-install.sh
+ rm -fr '/mnt/data/*'
+ rm -fr /mnt/data/odoo-addons-dir
+ mkdir -p /mnt/data/odoo-addons-dir
+ cd /mnt/data/odoo-addons-dir
+ curl -sSL https://github.com/oca/vertical-association/tarball/d370881ab90cf5e0195d38e27df3f34a440e9d30
+ tar zxf - --strip-components=1
+ INSTALL_METHOD=oca_install_addons
+ [[ oca_install_addons == \o\c\a\_\i\n\s\t\a\l\l\_\a\d\d\o\n\s ]]
+ oca_install_addons
+ setuptools-odoo-get-requirements --include-addons --addons-dir /mnt/data/odoo-addons-dir
/root/.local/pipx/shared/lib/python3.8/site-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/root/.local/pipx/shared/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
+ cat test-requirements.txt
odoo-addon-membership_extension>=16.0dev,<16.1dev
odoo>=16.0a,<16.1dev
+ pip install -r test-requirements.txt
Looking in indexes: https://wheelhouse.odoo-community.org/oca-simple-and-pypi
ERROR: Could not find a version that satisfies the requirement odoo-addon-membership_extension<16.1dev,>=16.0dev (from versions: 15.0.1.0.0.3)
ERROR: No matching distribution found for odoo-addon-membership_extension<16.1dev,>=16.0dev
```

**Comment by rafaelbn** [comment]
Hello @sbidoul , could you please give us a clue to solve this runboat log? https://github.com/OCA/vertical-association/pull/133#issuecomment-1359665739 @yajo do you have any idea? Thank you!

**Comment by sbidoul** [comment]
@rafaelbn membership_extension is not merged, hence not available for installation.

**Comment by fcvalgar** [comment]
@carmenbianca can you rebase? please.

**Comment by carmenbianca** [comment]
@rafaelbn Done.

Do you know which button I need to press to make sure that the ocabot rebase command works in the future?

**Comment by sbidoul** [comment]
> Do you know which button I need to press to make sure that the ocabot rebase command works in the future?

I don't think there is one if the source branch belongs to an organization fork as opposed to a personal account.

**Comment by pedrobaeza** [comment]
Yes, it's a problem/undesired feature of GitHub, that doesn't allow maintainers to push to organization branches. Last time I checked, they don't want to change this behavior.

**Comment by carmenbianca** [comment]
That's a pity :( Thank you for your swift answers @sbidoul @pedrobaeza

I'll add a low-priority discussion item about this for our next internal meeting.

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @carmenbianca

**Comment by fcvalgar** [comment]
internal @moduon MT-1834

**Review by PierrickBrun — APPROVED** [review]

**Pull request merged**
