### PR TITLE
[16.0][MIG] membership_extension

### PR DESCRIPTION
**Pull request by carmenbianca**
Ping @robinkeunen @PierrickBrun

We may need to drop the commit '[[FIX] membership_extension: Use latest start date for Membership Last Start Date](https://github.com/OCA/vertical-association/commit/63822ed42c12a5a5904e042eeef29fa6ad830491)' awaiting the resolving of #126

### CODE REVIEW

**Comment by carmenbianca** [comment]
@PierrickBrun The CI is now green :green_circle:

**Review by PierrickBrun — APPROVED** [review]

**Comment by carmenbianca** [comment]
@gurneyalex Apologies for the many pings. This also needs CLA verification. Thank you! :1st_place_medal:

**Comment by legalsylvain** [comment]
Hi @carmenbianca. I have a warning on the install : 

```2022-10-17 14:50:09,922 45215 WARNING pos_membership_extension odoo.addons.base.models.ir_model: Two fields (membership_categories, membership_category_ids) of res.partner() have the same label: Membership Categories. [Modules: membership_extension and membership_extension] ```

I guess that the second field ``membership_categories`` is a technical ones, and could be named 'Technical Membership Categories'. but not sure.

regards.

**Comment by carmenbianca** [comment]
@rafaelbn rebased

**Comment by rafaelbn** [comment]
Please @fcvalgar ! Thank you!

**Review by fcvalgar — APPROVED** [review]
Functional review ok

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
