### PR TITLE
[WIP] membership_sisterhood: New module to 14.0

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This module extends Odoo's membership management with the following features:

* Membership birth date
* Membership since date

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Why not using https://github.com/OCA/partner-contact/tree/14.0/partner_contact_birthdate You also have `start_date` in membership extension; you can generate the proper membership lines to fit the proper dates (we've got a customer whose member can date up to 1925 :)).

**Comment by primes2h** [comment]
> This module extends Odoo's membership management with the following features:
> 
>     * Membership birth date
> 
>     * Membership since date

Hi @manuelcalerosolis, thank you for the PR.

These features in some way are already fulfilled by this module:
https://github.com/OCA/partner-contact/tree/14.0/partner_contact_birthdate

There are also modules for gender and birthplace (open PR)
https://github.com/OCA/partner-contact/tree/14.0/partner_contact_gender
https://github.com/OCA/partner-contact/pull/1196

**Comment by manuelcalerosolis** [comment]
@chienandalu, I was looking at the two possibilities that you mention, I can really use the date of birth module. 

The problem is that the start date of membership in a brotherhood is a very relevant piece of information, due to the issue of seniority as a member. 

Creating a membership line for each member seems to me to be a very cumbersome issue, considering that there are thousands of associates, who already come from another application. 

In addition, this module will have more particularities that religious organizations have and that are not contemplated in the standard module, that is why I have decided to open myself to a new module.

**Comment by rafaelbn** [comment]
Hello @manuelcalerosolis ,

Is this still a WIP?

Thanks

**Comment by manuelcalerosolis** [comment]
@rafaelbn nice to see you.

Yes, it is still in process, it is a project that I do outside of my work for an association with which I collaborate.

**Pull request closed without merging**
