### PR TITLE
[17.0][MIG] membership_extension: Migration to 17.0

### PR DESCRIPTION
**Pull request by RogerSans**
Standard migration
T-6475

@HaraldPanten 
@ValentinVinagre

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
@RogerSans The migration commit has an incorrect name

**Comment by RogerSans** [comment]
Solved THNX

**Review by HaraldPanten — APPROVED** [review]

**Review by Tisho99 — CHANGES_REQUESTED** [review]
Code and functional review.

The migration seems good

However, can you remove the membership_variable_period module from this migration. 

Migrations PR's should only migrate one module

@RogerSans

**Comment by RogerSans** [comment]
> Code and functional review.
> 
> The migration seems good
> 
> However, can you remove the membership_variable_period module from this migration.
> 
> Migrations PR's should only migrate one module
> 
> @RogerSans

Changed. THNX

**Comment by HaraldPanten** [comment]
@RogerSans  don't you still have changes in membership_variable_period module ? Check pre-commit commit as well and make sure you are not including anything from membership_variable_period_module.

THX

**Comment by RogerSans** [comment]
@HaraldPanten 
Yes, I have made the changes that Alberto requested. However, in the pre-commit fix there is a reference to this module since a problem with a false error given by flake8 in the lambda function had to be solved. If I have to do it in a different pr I will change it.

**Comment by ValentinVinagre** [comment]
@RogerSans please remove the "membership_variable_period" module.

**Comment by rafaelbn** [comment]
MT-7084 @moduon please @edlopen @fcvalgar review 😄 ❤️

**Comment by RogerSans** [comment]
@HaraldPanten @ValentinVinagre done

**Review by edlopen — APPROVED** [review]
LGTM. Code and functional review here. Thank you for the migration!

**Review by fcvalgar — APPROVED** [review]
Functional review. 
LGTM, thank you @RogerSans

**Comment by HaraldPanten** [comment]
THX for the reviews, @fcvalgar and @edlopen 👍 

I think that now that we have functional and technical reviews, this PR is ready to merge. Could you do that, @rafaelbn ?

**Comment by rafaelbn** [comment]
@ValentinVinagre do you agree to merge?

**Pull request merged**
