### PR TITLE
[14.0][MIG] - membership_variable_period

### PR DESCRIPTION
**Pull request by sbejaoui**
needs: https://github.com/OCA/vertical-association/pull/108

### CODE REVIEW

**Comment by sbejaoui** [comment]
cc/ @rousseldenis

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by victoralmau — APPROVED** [review]
Code review OK, although `membership_extension` needs to be merge first.

**Comment by victoralmau** [comment]
Please, rebase to check Travis.

**Review by victoralmau — APPROVED** [review]
Re-launched Travis is green.

**Pull request merged**
