### PR TITLE
[8.0][FIX][membership_autoextend] date_to is in the future

### PR DESCRIPTION
**Pull request by hbrunn**
do we want a migration script for people who figured out they must fill in negative days but never bothered to come here and create an issue?

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
@hbrunn please could you review Travis? Thanks

```2017-05-10 21:10:09,242 5670 ERROR openerp_test openerp.addons.membership_autoextend.tests.test_membership_autoextend: FAIL: test_membership_autoextend (openerp.addons.membership_autoextend.tests.test_membership_autoextend.TestMembershipAutoextend)

2017-05-10 21:10:09,242 5670 ERROR openerp_test openerp.addons.membership_autoextend.tests.test_membership_autoextend: Traceback (most recent call last):

2017-05-10 21:10:09,242 5670 ERROR openerp_test openerp.addons.membership_autoextend.tests.test_membership_autoextend: `   File "/home/travis/build/OCA/vertical-association/membership_autoextend/tests/test_membership_autoextend.py", line 88, in test_membership_autoextend
```

**Review by rafaelbn — CHANGES_REQUESTED** [review]
Please review Travis errors

**Comment by pedrobaeza** [comment]
@hbrunn are you going to continue with this? Can you check Travis status?

**Comment by hbrunn** [comment]
that's a part of a pet project, so I won't really work on this any time soon. But the bug looks obvious enough to me actually. Would have to dive into the code tro see if the test errors are related or not

**Comment by pedrobaeza** [comment]
Try with a rebase first to see

**Pull request closed without merging**
