### PR TITLE
[17.0][MIG] website_membership_random_order: Migration to 17.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 17.0

@Tecnativa TT51560

### CODE REVIEW

**Comment by chienandalu** [comment]
Testing on runbot, I set serveral free members. They show up always in the same order:

image

**Comment by victoralmau** [comment]
The random mode does not work with free members, only with `membership.membership_line` records. 
This behavior is the same as in previous versions.

**Comment by chienandalu** [comment]
Shouldn't it be in the known issues section?

**Review by pedrobaeza — APPROVED** [review]
OK to add the mention about free members.

**Review by chienandalu — APPROVED** [review]
:+1:

**Pull request merged**
