### PR TITLE
[13.0][MIG] membership_variable_period

### PR DESCRIPTION
**Pull request by astirpe**
Depends on https://github.com/OCA/vertical-association/pull/83

Includes:

- [x] https://github.com/OCA/vertical-association/pull/90

### CODE REVIEW

**Comment by TheCloneMaster** [comment]
Functional testing, works as expected
-Mario

**Comment by pedrobaeza** [comment]
@astirpe please rebase

**Comment by pedrobaeza** [comment]
Please do properly the steps with pre-commit stuff previous to migration and squashing migration commits.

**Review by chienandalu — APPROVED** [review]
LGTM :+1:

**Pull request merged**
